/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_planes_javafx_PlaneRoundJavaFx */

#ifndef _Included_com_planes_javafx_PlaneRoundJavaFx
#define _Included_com_planes_javafx_PlaneRoundJavaFx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_planes_javafx_PlaneRoundJavaFx
 * Method:    createPlanesRound
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_planes_javafx_PlaneRoundJavaFx_createPlanesRound
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
