/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_planes_javafx_PlaneRoundJavaFx */

#ifndef _Included_com_planes_javafx_PlaneRoundJavaFx
#define _Included_com_planes_javafx_PlaneRoundJavaFx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_planes_javafx_PlaneRoundJavaFx
 * Method:    createPlanesRound
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_planes_javafx_PlaneRoundJavaFx_createPlanesRound
  (JNIEnv *, jobject);

/*
 * Class:     com_planes_javafx_PlaneRoundJavaFx
 * Method:    getRowNo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_planes_javafx_PlaneRoundJavaFx_getRowNo
  (JNIEnv *, jobject);

/*
 * Class:     com_planes_javafx_PlaneRoundJavaFx
 * Method:    getColNo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_planes_javafx_PlaneRoundJavaFx_getColNo
  (JNIEnv *, jobject);

/*
 * Class:     com_planes_javafx_PlaneRoundJavaFx
 * Method:    getPlaneNo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_planes_javafx_PlaneRoundJavaFx_getPlaneNo
  (JNIEnv *, jobject);

/*
 * Class:     com_planes_javafx_PlaneRoundJavaFx
 * Method:    getPlaneSquareType
 * Signature: (IIZ)I
 */
JNIEXPORT jint JNICALL Java_com_planes_javafx_PlaneRoundJavaFx_getPlaneSquareType
  (JNIEnv *, jobject, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
