name: planes
version: 0.3.10.1
grade: stable
adopt-info: planes

confinement: devmode
base: core20

apps:
  planes:
    common-id: com.planes.desktop
    command: planes
    extensions:
      - kde-neon


parts:
   planes:
    parse-info:
      - planes.metainfo.xml
    plugin: cmake
    build-snaps:
      - kde-frameworks-5-91-qt-5-15-3-core20-sdk
      - kde-frameworks-5-91-qt-5-15-3-core20
    source: https://github.com/xxxcucus/planes.git
    source-subdir: c_plus_plus
    source-branch: 0.3.10.1-branch
